# Generated by Django 3.1.3 on 2020-11-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201130_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='MyOwnToken',
        ),
    ]
