# Generated by Django 3.1.3 on 2020-11-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201130_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
